Resources:
  StagingCatalogJob:
    Type: AWS::Glue::Job
    Properties:
      Description: Glue job to move data from raw to staging
      Name: job-${self:custom.project}
      Role: !GetAtt stagingCatalogRole.Arn
      ExecutionProperty:
        MaxConcurrentRuns: ${self:custom.jobMaxConcurrentRuns}
      JobRunQueuingEnabled: true
      MaxRetries: 0
      NumberOfWorkers: ${self:custom.jobNumberOfWorkers}
      WorkerType: G.1X
      GlueVersion: ${self:custom.glueVersion}
      DefaultArguments:
        "--job-language": "python"
        "--TempDir": !Sub "s3://${self:custom.bucketNameProject}/tmp/"
        "--enable-metrics": "true"
        "--JOB_NAME": "${self:custom.project}"
        "--extra-py-files": ${self:custom.extraPythonFiles}
        "--BUCKET_NAME_INPUT": ${self:custom.bucketNameRaw}
        "--PATH_NAME_INPUT": ""
        "--BUCKET_NAME_OUTPUT": ${self:custom.bucketNameStaging}
        "--PATH_NAME_OUTPUT": ""
        "--CATALOG_DATABASE": ""
        "--CATALOG_TABLE": ""
        "--MERGE_KEYS": ""
        "--PARTITION_KEY": ""
        "--PARAMETERS_SCHEMA": ""
      Command:
        Name: glueetl
        ScriptLocation: s3://${self:custom.bucketNameProject}/${self:custom.projectBucketJobsPath}/catalog_transversal.py

  StagingCatalogJobV2:
    Type: AWS::Glue::Job
    Properties:
      Description: Glue job to move data from raw to staging
      Name: ${self:custom.nameJobStagingCatalog}
      Role: !GetAtt stagingCatalogRole.Arn
      ExecutionProperty:
        MaxConcurrentRuns: ${self:custom.jobMaxConcurrentRuns}
      JobRunQueuingEnabled: true
      MaxRetries: 0
      NumberOfWorkers: ${self:custom.jobNumberOfWorkers}
      WorkerType: ${self:custom.jobWorkerType}
      GlueVersion: ${self:custom.glueVersion}
      DefaultArguments:
        "--job-language": "python"
        "--TempDir": !Sub "s3://${self:custom.bucketNameProject}/tmp/"
        "--enable-metrics": "true"
        "--additional-python-modules": "openpyxl==3.1.5"
        "--extra-py-files": ${self:custom.extraPythonFiles}
        "--job_name": ${self:custom.nameJobStagingCatalog}
        "--bucket_name_raw": ${self:custom.bucketNameRaw}
        "--path_name_raw": ""
        "--bucket_name_schema": ${self:custom.bucketNameSchema}
        "--bucket_name_staging": ${self:custom.bucketNameStaging}
        "--stage": ${self:custom.stage}
        "--path_name_staging": ""
        "--catalog_database": ""
        "--catalog_table": ""
        "--merge_keys": ""
        "--partition_key_staging": ""
        "--partition_key_raw": ""
        "--excel_sheet": ""
        "--partition_key_raw_path": ""
        "--file_name_excel": ""
        "--process_type": ""
        "--date_type": ""
        "--start_date": ""
        "--end_date": ""
        "--region": "${self:custom.region}"
        "--event_bus_name":  ${self:custom.observabilityEventBusName}
        "--notifications_transversal_lambda_name": ${self:custom.transversalStepNotificationsName}
      Command:
        Name: glueetl
        ScriptLocation: s3://${self:custom.bucketNameProject}/${self:custom.projectBucketJobsPath}/catalog_transversal_v2.py
